apiVersion: v2
name: sentry-relay
description: Sentry event forwarding and ingestion service
type: application
version: 0.1.0
appVersion: "23.2.0"
maintainers:
  - name: skriptfabrik
    url: https://github.com/skriptfabrik
