{{- if not .Values.directus.extra.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "directus.fullname" . }}
  labels:
    {{- include "directus.labels" . | nindent 4 }}
type: Opaque
data:
{{- if has .Values.directus.database.client (list "pg" "postgres" "mysql" "oracledb" "mssql") }}
  DB_USER: {{ .Values.directus.database.user | b64enc }}
  DB_PASSWORD: {{ .Values.directus.database.password | b64enc }}
{{- end }}
{{- if .Values.directus.redis }}
  REDIS: {{ .Values.directus.redis | b64enc }}
{{- end }}
  KEY: {{ .Values.directus.security.key | b64enc }}
  SECRET: {{ .Values.directus.security.secret | b64enc }}
{{- if has "gcs" .Values.directus.fileStorage.locations }}
  STORAGE_GCS_KEY: {{ .Values.directus.fileStorage.gcs.key | b64enc }}
{{- end }}
{{- if .Values.directus.authentication.providers }}
{{- if has "google" .Values.directus.authentication.providers }}
  AUTH_GOOGLE_CLIENT_ID: {{ .Values.directus.authentication.google.clientID | b64enc }}
  AUTH_GOOGLE_CLIENT_SECRET: {{ .Values.directus.authentication.google.clientSecret | b64enc }}
{{- end }}
{{- end }}
{{- if .Values.directus.adminAccount.enabled }}
  ADMIN_EMAIL: {{ .Values.directus.adminAccount.email | b64enc }}
  ADMIN_PASSWORD: {{ .Values.directus.adminAccount.password | b64enc }}
{{- end }}
{{- range $name, $value := .Values.directus.extra.secret }}
{{- if not (empty $value) }}
  {{ $name }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
{{- end }}
