apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sentry-relay.fullname" . }}
  labels:
    {{- include "sentry-relay.labels" . | nindent 4 }}
data:
  config.yml: |-
    relay:
      mode: {{ .Values.config.mode }}
      host: {{ .Values.config.host | quote }}
